# Generated by Django 4.0.4 on 2022-05-29 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_teacherstudent_remove_student_teacher_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherstudent',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning', to='school.student', verbose_name='Студенты'),
        ),
        migrations.AlterField(
            model_name='teacherstudent',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning', to='school.teacher', verbose_name='Учителя'),
        ),
    ]
